powershell "(New-Object System.Net.WebClient).DownloadFile('https://www.dropbox.com/s/6jcrajlegy8w9ta/obj_final.weights?dl=1','obj_final.weights')"
powershell "(New-Object System.Net.WebClient).DownloadFile('https://www.dropbox.com/s/v2lmc5xs4x69zyg/obj.cfg?dl=1','obj.cfg')"
powershell "(New-Object System.Net.WebClient).DownloadFile('https://www.dropbox.com/s/0xued029gwwkotu/obj.names?dl=1','obj.names')"
powershell "(New-Object System.Net.WebClient).DownloadFile('https://www.dropbox.com/s/9mzihhuoue3q6hr/cudnn64_5.dll?dl=1','cudnn64_5.dll')"
powershell "(New-Object System.Net.WebClient).DownloadFile('https://www.dropbox.com/s/g82rncix38e734z/YOLOv2_SE.dll?dl=1','YOLOv2_SE.dll')"